
  // This file was automatically generated. Edits will be overwritten

  export interface Typegen0 {
        '@@xstate/typegen': true;
        internalEvents: {
          "done.invoke.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]": { type: "done.invoke.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer.checkingIssuerTrust:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer.checkingIssuerTrust:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.credentialDownloadFromOffer:invocation[0]": { type: "done.invoke.issuersMachine.credentialDownloadFromOffer:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.displayIssuers:invocation[0]": { type: "done.invoke.issuersMachine.displayIssuers:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]": { type: "done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]": { type: "done.invoke.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]": { type: "done.invoke.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.downloadCredentials.tokenRequest:invocation[0]": { type: "done.invoke.issuersMachine.downloadCredentials.tokenRequest:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.downloadCredentials:invocation[0]": { type: "done.invoke.issuersMachine.downloadCredentials:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.downloadIssuerWellknown:invocation[0]": { type: "done.invoke.issuersMachine.downloadIssuerWellknown:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.getCredentialTypes:invocation[0]": { type: "done.invoke.issuersMachine.getCredentialTypes:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.proccessingCredential:invocation[0]": { type: "done.invoke.issuersMachine.proccessingCredential:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.storing:invocation[0]": { type: "done.invoke.issuersMachine.storing:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"done.invoke.issuersMachine.verifyingCredential:invocation[0]": { type: "done.invoke.issuersMachine.verifyingCredential:invocation[0]"; data: unknown; __tip: "See the XState TS docs to learn how to strongly type this." };
"error.platform.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]": { type: "error.platform.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.constructProof:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.constructProof:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.sendTokenResponse:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.sendTokenResponse:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.sendTxCode:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.sendTxCode:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]"; data: unknown };
"error.platform.issuersMachine.credentialDownloadFromOffer:invocation[0]": { type: "error.platform.issuersMachine.credentialDownloadFromOffer:invocation[0]"; data: unknown };
"error.platform.issuersMachine.displayIssuers:invocation[0]": { type: "error.platform.issuersMachine.displayIssuers:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadCredentials.constructProof:invocation[0]": { type: "error.platform.issuersMachine.downloadCredentials.constructProof:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]": { type: "error.platform.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]": { type: "error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]": { type: "error.platform.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadCredentials.sendTokenResponse:invocation[0]": { type: "error.platform.issuersMachine.downloadCredentials.sendTokenResponse:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadCredentials.tokenRequest:invocation[0]": { type: "error.platform.issuersMachine.downloadCredentials.tokenRequest:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadCredentials:invocation[0]": { type: "error.platform.issuersMachine.downloadCredentials:invocation[0]"; data: unknown };
"error.platform.issuersMachine.downloadIssuerWellknown:invocation[0]": { type: "error.platform.issuersMachine.downloadIssuerWellknown:invocation[0]"; data: unknown };
"error.platform.issuersMachine.getCredentialTypes:invocation[0]": { type: "error.platform.issuersMachine.getCredentialTypes:invocation[0]"; data: unknown };
"error.platform.issuersMachine.verifyingCredential:invocation[0]": { type: "error.platform.issuersMachine.verifyingCredential:invocation[0]"; data: unknown };
"xstate.init": { type: "xstate.init" };
        };
        invokeSrcNameMap: {
          "addIssuerToTrustedIssuers": "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.addingIssuerToTrustedIssuers:invocation[0]";
"cacheIssuerWellknown": "done.invoke.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]";
"checkIssuerIdInStoredTrustedIssuers": "done.invoke.issuersMachine.credentialDownloadFromOffer.checkingIssuerTrust:invocation[0]" | "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]";
"constructAndSendProofForTrustedIssuers": "done.invoke.issuersMachine.downloadCredentials.constructProof:invocation[0]";
"constructProof": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.constructProof:invocation[0]";
"downloadCredential": "done.invoke.issuersMachine.downloadCredentials:invocation[0]";
"downloadCredentialFromOffer": "done.invoke.issuersMachine.credentialDownloadFromOffer:invocation[0]";
"downloadIssuerWellknown": "done.invoke.issuersMachine.downloadIssuerWellknown:invocation[0]";
"downloadIssuersList": "done.invoke.issuersMachine.displayIssuers:invocation[0]";
"generateKeyPair": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]";
"getCredentialTypes": "done.invoke.issuersMachine.getCredentialTypes:invocation[0]";
"getKeyOrderList": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]";
"getKeyPair": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]";
"isUserSignedAlready": "done.invoke.issuersMachine.storing:invocation[0]";
"sendConsentGiven": "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]";
"sendConsentNotGiven": "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentNotGiven:invocation[0]";
"sendTokenRequest": "done.invoke.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.tokenRequest:invocation[0]";
"sendTokenResponse": "done.invoke.issuersMachine.credentialDownloadFromOffer.sendTokenResponse:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.sendTokenResponse:invocation[0]";
"sendTxCode": "done.invoke.issuersMachine.credentialDownloadFromOffer.sendTxCode:invocation[0]";
"updateCredential": "done.invoke.issuersMachine.proccessingCredential:invocation[0]";
"verifyCredential": "done.invoke.issuersMachine.verifyingCredential:invocation[0]";
        };
        missingImplementations: {
          actions: "loadKeyPair" | "logDownloaded" | "resetCredentialOfferFlowType" | "resetError" | "resetLoadingReason" | "resetQrData" | "resetRequestConsentToTrustIssuer" | "resetRequestTxCode" | "resetSelectedCredentialType" | "resetSelectedIssuer" | "resetVerificationErrorMessage" | "resetVerificationResult" | "sendBackupEvent" | "sendDownloadingFailedToVcMeta" | "sendErrorEndEvent" | "sendImpressionEvent" | "sendSuccessEndEvent" | "setAccessToken" | "setCNonce" | "setCredential" | "setCredentialConfigurationId" | "setCredentialOfferCredentialType" | "setCredentialOfferFlowType" | "setCredentialOfferIssuer" | "setCredentialOfferIssuerWellknownResponse" | "setCredentialTypeListDownloadFailureError" | "setCredentialWrapper" | "setError" | "setIssuerDisplayDetails" | "setIssuers" | "setLoadingReasonAsDisplayIssuers" | "setLoadingReasonAsDownloadingCredentials" | "setLoadingReasonAsSettingUp" | "setMetadataInCredentialData" | "setPrivateKey" | "setPublicKey" | "setQrData" | "setRequestConsentToTrustIssuer" | "setRequestTxCode" | "setSelectedCredentialIssuer" | "setSelectedCredentialType" | "setSelectedIssuerId" | "setSelectedIssuers" | "setSelectedKey" | "setSupportedCredentialTypes" | "setTokenRequestObject" | "setTokenResponseObject" | "setTxCode" | "setTxCodeDisplayDetails" | "setVCMetadata" | "setVerifiableCredential" | "setVerificationResult" | "setWellknwonKeyTypes" | "storeKeyPair" | "storeVcMetaContext" | "storeVcsContext" | "storeVerifiableCredentialData" | "storeVerifiableCredentialMeta" | "updateIssuerFromWellknown" | "updateVerificationErrorMessage";
          delays: never;
          guards: "canSelectIssuerAgain" | "hasUserCancelledBiometric" | "isCredentialOfferFlow" | "isIssuerIdInTrustedIssuers" | "isKeyTypeNotFound" | "isSignedIn" | "isVerificationPendingBecauseOfNetworkIssue" | "shouldFetchIssuersAgain";
          services: "addIssuerToTrustedIssuers" | "cacheIssuerWellknown" | "checkIssuerIdInStoredTrustedIssuers" | "constructAndSendProofForTrustedIssuers" | "constructProof" | "downloadCredential" | "downloadCredentialFromOffer" | "downloadIssuerWellknown" | "downloadIssuersList" | "generateKeyPair" | "getCredentialTypes" | "getKeyOrderList" | "getKeyPair" | "isUserSignedAlready" | "sendConsentGiven" | "sendConsentNotGiven" | "sendTokenRequest" | "sendTokenResponse" | "sendTxCode" | "updateCredential" | "verifyCredential";
        };
        eventsCausingActions: {
          "loadKeyPair": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]";
"logDownloaded": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"resetCredentialOfferFlowType": "RESET_ERROR" | "TRY_AGAIN" | "done.invoke.issuersMachine.verifyingCredential:invocation[0]";
"resetError": "RESET_ERROR" | "TRY_AGAIN";
"resetLoadingReason": "CANCEL" | "RESET_ERROR" | "done.invoke.issuersMachine.displayIssuers:invocation[0]" | "error.platform.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.constructProof:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendTokenResponse:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendTxCode:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.constructProof:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.sendTokenResponse:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.tokenRequest:invocation[0]" | "error.platform.issuersMachine.downloadCredentials:invocation[0]" | "error.platform.issuersMachine.downloadIssuerWellknown:invocation[0]" | "error.platform.issuersMachine.getCredentialTypes:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"resetQrData": "CANCEL";
"resetRequestConsentToTrustIssuer": "CANCEL" | "ON_CONSENT_GIVEN" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]";
"resetRequestTxCode": "CANCEL" | "TX_CODE_RECEIVED" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendTxCode:invocation[0]";
"resetSelectedCredentialType": "CANCEL";
"resetSelectedIssuer": "QR_CODE_SCANNED";
"resetVerificationErrorMessage": "RESET_VERIFY_ERROR";
"resetVerificationResult": "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"sendBackupEvent": "done.invoke.issuersMachine.storing:invocation[0]";
"sendDownloadingFailedToVcMeta": "CANCEL" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.constructProof:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendTokenResponse:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendTxCode:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.constructProof:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]";
"sendErrorEndEvent": "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"sendImpressionEvent": "done.invoke.issuersMachine.displayIssuers:invocation[0]";
"sendSuccessEndEvent": "done.invoke.issuersMachine.verifyingCredential:invocation[0]";
"setAccessToken": "done.invoke.issuersMachine.downloadCredentials.tokenRequest:invocation[0]";
"setCNonce": "PROOF_REQUEST";
"setCredential": "done.invoke.issuersMachine.credentialDownloadFromOffer:invocation[0]";
"setCredentialConfigurationId": "done.invoke.issuersMachine.credentialDownloadFromOffer:invocation[0]";
"setCredentialOfferCredentialType": "done.invoke.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]";
"setCredentialOfferFlowType": "QR_CODE_SCANNED";
"setCredentialOfferIssuer": "done.invoke.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]";
"setCredentialOfferIssuerWellknownResponse": "done.invoke.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]";
"setCredentialTypeListDownloadFailureError": "error.platform.issuersMachine.getCredentialTypes:invocation[0]";
"setCredentialWrapper": "done.invoke.issuersMachine.downloadCredentials:invocation[0]" | "done.invoke.issuersMachine.proccessingCredential:invocation[0]";
"setError": "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.constructProof:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendTokenResponse:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendTxCode:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer:invocation[0]" | "error.platform.issuersMachine.displayIssuers:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.constructProof:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.sendTokenResponse:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.tokenRequest:invocation[0]" | "error.platform.issuersMachine.downloadCredentials:invocation[0]" | "error.platform.issuersMachine.downloadIssuerWellknown:invocation[0]";
"setIssuerDisplayDetails": "TRUST_ISSUER_CONSENT_REQUEST";
"setIssuers": "done.invoke.issuersMachine.displayIssuers:invocation[0]";
"setLoadingReasonAsDisplayIssuers": "TRY_AGAIN";
"setLoadingReasonAsDownloadingCredentials": "ON_CONSENT_GIVEN" | "QR_CODE_SCANNED" | "SELECTED_CREDENTIAL_TYPE" | "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]";
"setLoadingReasonAsSettingUp": "SELECTED_ISSUER" | "TRY_AGAIN";
"setMetadataInCredentialData": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"setPrivateKey": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]";
"setPublicKey": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]";
"setQrData": "QR_CODE_SCANNED";
"setRequestConsentToTrustIssuer": "done.invoke.issuersMachine.credentialDownloadFromOffer.checkingIssuerTrust:invocation[0]";
"setRequestTxCode": "TX_CODE_REQUEST";
"setSelectedCredentialIssuer": "PROOF_REQUEST" | "TRUST_ISSUER_CONSENT_REQUEST";
"setSelectedCredentialType": "SELECTED_CREDENTIAL_TYPE";
"setSelectedIssuerId": "SELECTED_ISSUER";
"setSelectedIssuers": "SELECTED_ISSUER";
"setSelectedKey": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]";
"setSupportedCredentialTypes": "done.invoke.issuersMachine.getCredentialTypes:invocation[0]";
"setTokenRequestObject": "TOKEN_REQUEST";
"setTokenResponseObject": "done.invoke.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.tokenRequest:invocation[0]";
"setTxCode": "TX_CODE_RECEIVED";
"setTxCodeDisplayDetails": "TX_CODE_REQUEST";
"setVCMetadata": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"setVerifiableCredential": "done.invoke.issuersMachine.downloadCredentials:invocation[0]" | "done.invoke.issuersMachine.proccessingCredential:invocation[0]";
"setVerificationResult": "done.invoke.issuersMachine.verifyingCredential:invocation[0]";
"setWellknwonKeyTypes": "PROOF_REQUEST";
"storeKeyPair": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]";
"storeVcMetaContext": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"storeVcsContext": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"storeVerifiableCredentialData": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"storeVerifiableCredentialMeta": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"updateIssuerFromWellknown": "done.invoke.issuersMachine.downloadIssuerWellknown:invocation[0]";
"updateVerificationErrorMessage": "error.platform.issuersMachine.verifyingCredential:invocation[0]";
        };
        eventsCausingDelays: {
          
        };
        eventsCausingGuards: {
          "canSelectIssuerAgain": "TRY_AGAIN";
"hasUserCancelledBiometric": "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.constructProof:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.downloadCredentials:invocation[0]";
"isCredentialOfferFlow": "TRY_AGAIN";
"isIssuerIdInTrustedIssuers": "done.invoke.issuersMachine.credentialDownloadFromOffer.checkingIssuerTrust:invocation[0]" | "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]";
"isKeyTypeNotFound": "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]";
"isSignedIn": "done.invoke.issuersMachine.storing:invocation[0]";
"isVerificationPendingBecauseOfNetworkIssue": "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"shouldFetchIssuersAgain": "TRY_AGAIN";
        };
        eventsCausingServices: {
          "addIssuerToTrustedIssuers": "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]" | "error.platform.issuersMachine.credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList:invocation[0]";
"cacheIssuerWellknown": "done.invoke.issuersMachine.credentialDownloadFromOffer:invocation[0]";
"checkIssuerIdInStoredTrustedIssuers": "TRUST_ISSUER_CONSENT_REQUEST" | "done.invoke.issuersMachine.credentialDownloadFromOffer.sendConsentGiven:invocation[0]";
"constructAndSendProofForTrustedIssuers": "TRY_AGAIN" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.generateKeyPair:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]";
"constructProof": "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.generateKeyPair:invocation[0]" | "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]";
"downloadCredential": "SELECTED_CREDENTIAL_TYPE";
"downloadCredentialFromOffer": "QR_CODE_SCANNED";
"downloadIssuerWellknown": "SELECTED_ISSUER" | "TRY_AGAIN";
"downloadIssuersList": "CANCEL" | "TRY_AGAIN" | "xstate.init";
"generateKeyPair": "error.platform.issuersMachine.credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore:invocation[0]" | "error.platform.issuersMachine.downloadCredentials.keyManagement.getKeyPairFromKeystore:invocation[0]";
"getCredentialTypes": "done.invoke.issuersMachine.downloadIssuerWellknown:invocation[0]";
"getKeyOrderList": "PROOF_REQUEST";
"getKeyPair": "TRY_AGAIN" | "done.invoke.issuersMachine.credentialDownloadFromOffer.keyManagement.setSelectedKey:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.keyManagement.setSelectedKey:invocation[0]";
"isUserSignedAlready": "done.invoke.issuersMachine.verifyingCredential:invocation[0]" | "error.platform.issuersMachine.verifyingCredential:invocation[0]";
"sendConsentGiven": "ON_CONSENT_GIVEN" | "done.invoke.issuersMachine.credentialDownloadFromOffer.checkingIssuerTrust:invocation[0]";
"sendConsentNotGiven": "CANCEL";
"sendTokenRequest": "TOKEN_REQUEST";
"sendTokenResponse": "done.invoke.issuersMachine.credentialDownloadFromOffer.tokenRequest:invocation[0]" | "done.invoke.issuersMachine.downloadCredentials.tokenRequest:invocation[0]";
"sendTxCode": "TX_CODE_RECEIVED";
"updateCredential": "done.invoke.issuersMachine.cachingCredentialOfferIssuerWellknown:invocation[0]";
"verifyCredential": "done.invoke.issuersMachine.downloadCredentials:invocation[0]" | "done.invoke.issuersMachine.proccessingCredential:invocation[0]";
        };
        matchesStates: "cachingCredentialOfferIssuerWellknown" | "credentialDownloadFromOffer" | "credentialDownloadFromOffer.checkingIssuerTrust" | "credentialDownloadFromOffer.credentialOfferDownloadConsent" | "credentialDownloadFromOffer.idle" | "credentialDownloadFromOffer.keyManagement" | "credentialDownloadFromOffer.keyManagement.constructProof" | "credentialDownloadFromOffer.keyManagement.generateKeyPair" | "credentialDownloadFromOffer.keyManagement.getKeyPairFromKeystore" | "credentialDownloadFromOffer.keyManagement.setSelectedKey" | "credentialDownloadFromOffer.keyManagement.userCancelledBiometric" | "credentialDownloadFromOffer.sendConsentGiven" | "credentialDownloadFromOffer.sendConsentGiven.addingIssuerToTrustedIssuers" | "credentialDownloadFromOffer.sendConsentGiven.updatingTrustedIssuerList" | "credentialDownloadFromOffer.sendConsentNotGiven" | "credentialDownloadFromOffer.sendTokenResponse" | "credentialDownloadFromOffer.sendTxCode" | "credentialDownloadFromOffer.tokenRequest" | "credentialDownloadFromOffer.waitingForTxCode" | "displayIssuers" | "done" | "downloadCredentials" | "downloadCredentials.constructProof" | "downloadCredentials.idle" | "downloadCredentials.keyManagement" | "downloadCredentials.keyManagement.generateKeyPair" | "downloadCredentials.keyManagement.getKeyPairFromKeystore" | "downloadCredentials.keyManagement.setSelectedKey" | "downloadCredentials.keyManagement.userCancelledBiometric" | "downloadCredentials.sendTokenResponse" | "downloadCredentials.tokenRequest" | "downloadCredentials.userCancelledBiometric" | "downloadIssuerWellknown" | "error" | "getCredentialTypes" | "handleVCVerificationFailure" | "idle" | "proccessingCredential" | "selectingCredentialType" | "selectingIssuer" | "storing" | "verifyingCredential" | "waitingForQrScan" | { "credentialDownloadFromOffer"?: "checkingIssuerTrust" | "credentialOfferDownloadConsent" | "idle" | "keyManagement" | "sendConsentGiven" | "sendConsentNotGiven" | "sendTokenResponse" | "sendTxCode" | "tokenRequest" | "waitingForTxCode" | { "keyManagement"?: "constructProof" | "generateKeyPair" | "getKeyPairFromKeystore" | "setSelectedKey" | "userCancelledBiometric";
"sendConsentGiven"?: "addingIssuerToTrustedIssuers" | "updatingTrustedIssuerList"; };
"downloadCredentials"?: "constructProof" | "idle" | "keyManagement" | "sendTokenResponse" | "tokenRequest" | "userCancelledBiometric" | { "keyManagement"?: "generateKeyPair" | "getKeyPairFromKeystore" | "setSelectedKey" | "userCancelledBiometric"; }; };
        tags: never;
      }
  